# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'GymManager' do
  pod 'AFNetworking', '~> 3.0'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'UICKeyChainStore'
  pod 'TPKeyboardAvoiding'
  pod 'CCBottomRefreshControl'
end
